name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
      - name: Test with pytest
        run: |
          pip install pytest
          pytest --doctest-modules

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
      - name: Test with pytest
        run: |
          pip install yapf
          yapf *.py --in-place --style='{USE_TABS=true}'
          yapf lambdaHandlers/*.py --in-place --style='{USE_TABS=true}'
